name: Firmware Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install XC8
      uses: cactusdynamics/install-mplabxc8@v1

    - name: Build Firmware
      working-directory: firmware
      run: make